### ISSUE TITLE
add to community repo?

### ISSUE THREAD

**Issue by psifertex** [valgrind/binja-psx#1]
Any objection to me adding this to the community plugin repo? (https://github.com/Vector35/community-plugins/tree/master/plugins)

**Comment by PeterBortas** [comment]
No, go ahead. 

I've been meaning to do a PR myself, but every time I've looked at the code and felt that I should clean it up first. That's obviously not going to happen. :)

**Comment by psifertex** [comment]
Great, thanks. Done.
